### ISSUE TITLE
Remove unnecessary bulk

### ISSUE THREAD

**Issue by noplanman** [DiasPHPora/wp-to-diaspora#145]
A few features can be removed to save on code.

- [x] Replace AJAX pod updater with static list of pods that gets updated via plugin updates.
- [x] Remove custom code for SSL certificates (in help menu).

**Comment by noplanman** [comment]
@gutobenn Anything else you think isn't totally necessary?

I'm just trying to clean up as much as possible before taking the next step towards version 2.

**Comment by gutobenn** [comment]
@noplanman No
