### ISSUE TITLE
Scheduled posts publishing

### ISSUE THREAD

**Issue by aliakseiz** [DiasPHPora/wp-to-diaspora#149]
When post is scheduled and then published in Wordpress automatically, it doesn't appear in Diaspora.

Checked: if to publish post manually by pressing "Publish" button, it is synced to Diaspora correctly.

Plugin version 1.9.1
Wordpress 4.7.3

**Comment by noplanman** [comment]
What pod are you on?
Also, in the scheduled post, does it say that the post has been published to diaspora or not?

**Comment by aliakseiz** [comment]
I'm on joindiaspora.com and no, it doesn't say, that post has been published to diaspora.

When pressing "Schedule" button I see only 
> Post scheduled for: May 20, 2017 @ 11:24. Preview post

**Comment by noplanman** [comment]
I've tested it with joindiaspora and can't reproduce the problem.

Please give me a list of the plugins you have installed.
It might be an compatibility issue with another plugin.

Also, is this the first time you've tried scheduling or has this suddenly started happening?

**Comment by aliakseiz** [comment]
After a lot of testing, I've found that **WP to Twitter** plugin was interfering with **WP to Diaspora**.
Thanks for support!

**Comment by noplanman** [comment]
Hmm, we've had many issues with WP To Twitter. Was hoping they were all sorted by now.

I'll try to reproduce the problem to see if it can be fixed 👍 

(could you maybe give me extra info regarding the settings you have chosen for WP To Twitter?)
