### ISSUE TITLE
SSL error connecting to pod

### ISSUE THREAD

**Issue by haverholm** [DiasPHPora/wp-to-diaspora#150]
`Failed to initialise connection to pod "https://diasp.org". cURL error 35: Unknown SSL protocol error in connection to diasp.org:443`

Report here, with server admin, or to diasp.org?

**Comment by dmorley** [comment]
What version of curl?

**Comment by haverholm** [comment]
Beats me, but your qustion tells me I should get in touch with my own server admin ;)

**Comment by noplanman** [comment]
Do you have SSH access with your current hosting?
If yes, you can execute the following command:
`$ curl --version`

**Comment by haverholm** [comment]
Got this in my phpinfo: `cURL Information 7.21.0 ` 
Hope it helps (I try to keep my hands out of the server side).

**Comment by noplanman** [comment]
Looks like the protocols that you hosting provides aren't fully compatible with those of diasp.org.
Best to get in touch with your hosting and report this issue to them.

@dmorley This is the first report we've had, so I don't think it's a diasp.org issue. Unless you've set the SSL to be super-restrictive.

**Comment by dmorley** [comment]
I do have ssl pretty hardened, might try it against https://dev.diasp.org as I'll be moving to that config soon.

**Comment by noplanman** [comment]
@haverholm Did you manage to get this sorted with your hosting?
