### ISSUE TITLE
<pre> tags come out messed up

### ISSUE THREAD

**Issue by cares** [DiasPHPora/wp-to-diaspora#155]
First of all - thanks for your hard work and dedication to open source 👍 
i have a problem when using `<pre>` tags in wordpress.

i use it a lot for source code and bash commands.

but when publishing to diaspora ... they come out messed up.... do you have time and ressources to fix this or should i join the project? :-D

https://nerdpol.ch/posts/3814283

**Comment by noplanman** [comment]
Hi @cares, thanks for reporting this!

Of course you're welcome to help out, awesome :tada:

It looks like an issue with the markdown conversion, I'll check it out later today.

**Comment by noplanman** [comment]
Ok, this is a weird one 😕 

It's partly the way that the WordPress `wpautop` filter adds paragraphs automatically (and in some instances breaks multi-line code blocks) and it's also an issue in some cases with the way that those paragraphs are converted to Markdown by [HTML to Markdown](https://github.com/thephpleague/html-to-markdown) (the library we're using for the conversion).

I'd highly appreciate your kindly offered help on this one 😃

**Comment by noplanman** [comment]
@cares I've just released version 3.0.0.

Please give it a go and give me any feedback, thanks!
